rsksmart/rns-manager-react

src/app/components/IndicatorLight.js, src/app/containers/IndicatorLight.js, src/assets/css/sass/_header.scss, src/languages/es_uy.json, src/languages/ja.json, src/languages/ko.json, src/languages/pt_br.json, src/languages/ru.json, src/languages/zh_cn.json
Adds a third state to the indicator light: no wallet. 
**Only shows when no wallet (metamask, or nifty) is detected**
**On hover, a message is shown, using existing language, and when clicked, takes you to the setup page**
=> Indicator light no wallet

src/app/tabs/search/components/DomainStateComponent.js, src/app/tabs/search/containers/DomainStateContainer.js
This PR allows a user to commit to a domain but not register. Then search for a second domain and when clicking register, resets the registration process back to step 1.
The salt remains for domains that have been committed but not registered. So, if a user commits a domain, then searches and commits a second, the user can still go back to the original domain and will see that the commit process was saved.
Ref #155
=> Clear the registration process when clicking 'registration'

src/app/components/FooterComponent.js
Searched for `<a`, `<a `, `<Link ` and also found buttons with `window.open`. The footer was the only file left with links that were not opening in a new window.
Closes #141
=> Change footer addresses to open in new window.

src/app/auth/operations.js, src/app/auth/reducer.js
Rather than returning null with no autoredirect, return false. However, only change the state of showModal if the result is true.
This allows for autologin to work, and when it fails, it allows the user to click login and use different credentials. 
Finally, on Metamask, we listen for the accountsChanged event and we run start() to get the current account. This listener is not available in Nifty. 
Closes #176 
Closes #154
=> Handle autologin error

package.json, src/app/tabs/admin/components/AdminTabComponent.js, yarn.lock
Added scripts to deploy on Github pages. It works a little bit clunky but works. Later we can improve it with some env variables.
This is a **playground** environment. We can deploy any branch here and test it out.
Step on the branch you want to deploy on gh pages and
```
yarn run deploy
```
Github pages hosts page under `/rns-manager-react` url. This makes react router work bad. So, to use it.
1. Browse to https://rnsdomains.github.io/rns-manager-react/
2. Click on the logo, that will redirect to `/`
3. Use it 😄 
- I added a link at the bottom of current admin page to `/newAdmin`. I could not browse there via url...
- I'm the only one who can push to gh-pages 😬.
=> Add gh pages environment

src/app/auth/operations.js
Creates new localStorage item for domains that is an array for all of the previous domains. LocalStorage variable `name` still exists and is used for auto-login which still gets removed on logout.
Closes #216
=> Save array of previous logged in domains.

src/app/tabs/newAdmin/subdomains/operations.js, src/languages/en.json
Fixes bug where a subdomain would still persist if the delete action was interrupted by a browser refresh or closing. 
It also adds broswerNotifications that were missing in the original PR.
Closes #235
=> Subdomain clear bug

src/app/components/AddressInputComponent.js, src/app/components/AddressInputComponent.test.js, src/app/tabs/newAdmin/addresses/components/YourAddressesComponent.js, src/app/tabs/newAdmin/domainInfo/containers/TransferAddressContainer.js, src/app/tabs/newAdmin/reverse/components/ReverseComponent.js, src/app/tabs/newAdmin/reverse/containers/ReverseContainer.js, src/app/tabs/newAdmin/subdomains/components/SubdomainListComponent.js, src/assets/css/sass/admin/_index.scss, src/assets/css/sass/admin/_reverse.scss
updates:
- AddressInput Component shows correct checksum when input is RSK or ETH address
- Removes valueDisplay as relies on the existing validation and validationChainId parameters.
- Formats Reverse view page better to show entire label.
Steps to test: https://hackmd.io/DRRL5Yk1QiuZNauti_R5IQ?view
Closes #226
=> Address input checksum

src/app/tabs/registrar/operations.js
Uses a different endpoint for USD/RIF conversion.
Closes #220
CORS issue is resolved on localhost:3000. It may also need testing once deployed.
=> Change conversion rate API location.

src/app/tabs/newAdmin/addresses/operations.js
Definitive resolver `addr` and `setAddr` received a `uint256` as the chain parameter. It was sending the hexa that is used by the `MultichainResolver`
=> Use chainIndex with definitive resolver

src/app/tabs/resolve/operations.js
On the /Resolve page, use `chainIndex` not `chainId` when resolving an address.
=> Resolver Page use chainIndex in addr()

src/app/components/HeaderComponent.js, src/app/components/ScrollToTopComponent.js, src/app/components/index.js, src/app/index.js, src/app/tabs/home/components/HomeComponent.js, src/app/tabs/home/components/SearchBoxComponent.js, src/app/tabs/home/components/__snapshots__/SearchBoxComponent.test.js.snap, src/app/tabs/registrar/components/AutoLoginComponent.js, src/app/tabs/registrar/components/__snapshots__/AutoLoginComponent.test.js.snap, src/assets/css/sass/_columns.scss, src/assets/css/sass/_containers.scss, src/assets/css/sass/_footer.scss, src/assets/css/sass/_header.scss, src/assets/css/sass/home/_index.scss, src/assets/css/sass/registration/_registration-page.scss, src/assets/css/theming.css
QOL updates for the Manager on Mobile and Tablet
- Updated width in search box and submit for tablets and mobile, then removed top padding on mobile
- Search box curved blue back in and more subtle
- Add spacing below images to match amount on top.
- Call to Action boxes better sizing on tablet and breaks on mobile
- Reduce footer empty space while keeping curve gray 
- Smaller padding in .white section to reduce empty space
- Tighten up search results box
- Tighten spacing on steps section 
- reduce space above rental period time
- Step 2 was good on mobile and tablet
- Step 3, add space between login and register another button
- Reduce space on mobile between nav bar and content
- Use sticky-top for menu to allow menu on mobile to push content down when opened
- Remove stickiness on …
=> Mobile CSS for Landing page and Registration Process

src/app/tabs/newAdmin/resolver/operations.js, src/app/tabs/newAdmin/resolver/supportedInterfaces.json, src/app/tabs/newAdmin/resolver/types.js
- Public: Add the ADDR interface
- Both: Have MULTICOIN, MULTICHAIN, and ADDR call the getAllChainAddresses function which uses switch between the resolvers
=> Fix issue with supportedInterfaces not returning Public or Definitive addresses

src/app/helpers/transactionListener.js, src/app/tabs/newAdmin/addresses/operations.js, src/app/tabs/newAdmin/domainInfo/operations.js, src/app/tabs/newAdmin/resolver/operations.js, src/app/tabs/newAdmin/reverse/operations.js, src/app/tabs/newAdmin/subdomains/operations.js, src/app/tabs/registrar/operations.js
Fixes issue with `() => () =>` where the first is the parameters and the second is dispatch. All transactionListner will return dispatch(callback()) or dispatch(failedCallback()) depending on reason.
All listeners will now read the status from the blockchain and will execute `callback()` or `failedCallback` accordingly.
=> Transaction listeners and Failed Blockchain Response

src/app/tabs/newAdmin/components/AdminTabComponent.js, src/app/tabs/newAdmin/components/ExpiredDomainComponent.js, src/app/tabs/newAdmin/components/LetftNavComponent.js, src/app/tabs/newAdmin/components/ReclaimComponent.js, src/app/tabs/newAdmin/components/index.js, src/app/tabs/newAdmin/containers/AdminTabContainer.js, src/app/tabs/newAdmin/containers/ExpiredDomainContainer.js, src/app/tabs/newAdmin/containers/index.js, src/app/tabs/newAdmin/domainInfo/abis.json, src/app/tabs/newAdmin/domainInfo/components/DomainInfoComponent.js, src/app/tabs/newAdmin/domainInfo/components/RenewButtonComponent.js, src/app/tabs/newAdmin/domainInfo/components/RenewButtonComponent.test.js, src/app/tabs/newAdmin/domainInfo/containers/DomainInfoContainer.js, src/app/tabs/newAdmin/domainInfo/containers/RenewButtonContainer.js, src/app/tabs/newAdmin/domainInfo/operations.js, src/app/tabs/newAdmin/resolver/components/ViewContractAbiComponent.js, src/app/tabs/registrar/components/RegistrarComponent.js, src/config/contracts.local.json, src/languages/en.json, src/languages/es_uy.json, src/languages/ja.json, src/languages/ko.json, src/languages/pt_br.json, src/languages/ru.json, src/languages/zh_cn.json
This PR handles two situations. One of which I need help testing.
1) The domain is expired - Show a screen saying the domain is expired and suggest the user search for it again. Tested and works.
2) Don't show Renew or Transfer if the domain has not been migrated to FIFS. I tested this independently before implementing the domain expired and it worked. However, the rns-suite setup for the auction registrars is domains that are expired. So, when I log on to those, option 1 shows first.
=> Expired domains

.github/workflows/deploy.yml
Hi,
Keep in mind that the github action it's gonna work only if the yaml file that controls it (in this case, `.github/workflows/deploy` ) already is on place. Besides, someone with the right permissions on your repo must set the `secrets`.
You could reach me on Slack if any inconvinience arrises.
=> Added yaml for github action

package.json, src/app/tabs/newAdmin/resolver/components/NewRecordComponent.js, src/app/tabs/newAdmin/resolver/components/ViewRecordsComponent.js, yarn.lock
- Bump dependencies to support IPNS.
- Update placeholder text, add `ipns://` and remove `/ipfs` since it seems to only accept `ipfs://`
Continues from #341, I was unable to rebase that PR correctly.
=> Support IPNS

src/app/auth/operations.js, src/app/notifications/index.js, src/app/notifications/operations.js, src/app/tabs/admin/operations.js, src/app/tabs/multiChainResolver/operations.js, src/app/tabs/publicResolver/operations.js, src/app/tabs/renew/operations.js, src/app/tabs/stringResolver/operations.js
Fixes and issue that is causing the RNS Manager to break in production.
With the older admin, when a user would log into a domain, it would check against the domain's resolver to see if it was registered with the publicResolver. If so, it would dispatch a message to the notifications resolver, which was never implemented into the new admin.
This older code was using `window.web3` which is no longer provided by MetaMask. Updating this code to use the existing [getDomainResolver()](https://github.com/rnsdomains/rns-manager-react/blob/develop/src/app/tabs/newAdmin/resolver/operations.js#L63-L75) function resulted in a dependency cycle.  Since the notifications are no longer used, it was determined to remove this function and the references to it.
In addition, there was deprecated code still …
=> Remove check of resolver address from the notification's reducer

package.json, src/app/auth/operations.js, yarn.lock
Update rLogin to support add liquality wallet and updates the `eventListeners` to `on`. 
The checklist below shows the functions that worked. Surprisingly migrating with addresses, which uses two transactions, worked, while setting a subdomain's owner did not work.
The change to the listeners was also tested with Metamsk, Nifty, and WalletConnect.
=> Add Liquality Wallet

src/app/tabs/home/components/SearchBoxComponent.js, src/app/tabs/home/components/SearchBoxComponent.test.js, src/app/tabs/home/components/__snapshots__/SearchBoxComponent.test.js.snap, src/assets/css/sass/_bootstrapReset.scss, src/assets/css/sass/home/_searchBox.scss
- Converts the search term to lowercase before searching. Resolves #337 
- Removes auto-capitalization for mobile devices. Resolves #251
- Removes outline on landing search boxfocus`. Also removes the same outline for buttons. Resolves UX Feedback No.4
=> Convert search term to lowercase before searching.

package.json, src/app/auth/operations.js, tests/setupTests.js, yarn.lock
rLogin 0.1.2 has an issue where it does not run with Nifty. Bumping to the latest (breaking) version is a better solution for the long term. 
I needed to mock TextEncoder/TextDecoder for the jest test to run. Help came from here: https://stackoverflow.com/questions/57712235/referenceerror-textencoder-is-not-defined-when-running-react-scripts-test
=> Upgrade rLogin to v1.0.2

.github/workflows/gh-deploy.yml, package.json, src/app/components/PlausibleAnalytics.js, src/app/tabs/home/components/WalletCarousel.js, src/app/tabs/registrar/components/RegistrarComponent.js, src/assets/css/sass/_footer.scss, src/assets/css/sass/admin/_address.scss, src/assets/css/sass/admin/_resolver.scss, src/assets/css/sass/home/_index.scss, src/assets/img/caret-down.svg, src/assets/img/caret.svg, src/assets/img/home/bottom-background.svg, yarn.lock
**Portis Failing Build Findings:**
- The super class error is caused by the Portis package import. When this package is commented out and not added to the rLogin options, the app builds locally.
- The Portis package works correctly on the RIF Id Manager. The Id Manager uses an upgraded version of `react`, `react-dom`, and `react-scripts`.
- Rather than bumping all 3 packages, this PR bumped `react-scripts` to 4.0.0
Added Github pages deploy to test the build to work. It **builds correctly** see here: https://rsksmart.github.io/rns-manager-react/ . I see no reason this shouldn't work in production.
**Changes**
The new version of react-scripts required fixing some eslint issues.
- correct spacing indentions
- svg files that were in /public, need to be in /src
- SCSS/CSS importing URLs need …
=> Fix Portis build Error

.github/workflows/ci.yml, .github/workflows/deploy.yml, README.md
Updates ci, cd and readme to point to `main`. I pushed the branch even with `develop` and set its rules. We can then point `v2.1.6` to it (#444)
Reason: the last 3 releases were a pain due to branch conflicts
=> Deprecate master, move to main

package.json, src/app/auth/operations.js, src/app/tabs/newAdmin/addresses/operations.js, src/app/tabs/newAdmin/domainInfo/operations.js, src/app/tabs/newAdmin/operations.js, src/app/tabs/newAdmin/resolver/operations.js, src/app/tabs/newAdmin/reverse/operations.js, src/app/tabs/newAdmin/subdomains/operations.js, src/app/tabs/registrar/operations.js
rLogin provider for hardware devices do not use `.enable`
=> Fix enable

.github/workflows/gh-deploy.yml, README.md, package.json, src/app/components/FooterComponent.js, src/app/routes.js, src/app/tabs/newAdmin/addresses/components/YourAddressesComponent.js
The issue was caused by the homepage attribute being set to `.`. This was done so the GitHub pages deploy worked correctly. This used to work without issue with both production and GH environments. 
This is tested with the GitHub pages deployment and should work with in production. However, there is only one way to find out...
=> Fix broken images on deployment

src/app/tabs/search/operations.js
This PR Fixes a bug that rounds the price down instead of displaying the appropriate decimal value for available names on the home page for partner with discount percentage lower than 50%
=> fix: fix rounding error on price display for available name on home

src/assets/css/sass/home/_searchResults.scss
This PR fixes the issue where the result section was not rendering properly on smaller screens.
=> fix: issue fix for results section overlap on mobile screens

src/app/tabs/resolve/components/ResolveComponent.js
The behaviour reported in this [issue](https://rsklabs.atlassian.net/browse/REM-43) and the approach taken by this [fix](https://github.com/rsksmart/rns-manager-react/pull/559) doesn't apply here because in the case of the [disposable-main branch](https://github.com/rsksmart/rns-manager-react/tree/disposable-main) which uses the web3 library to interact with the RNS contract (which has the multichain support) directly, the updated version of this project which uses the rns-sdk has no support for multichain at the time of creating this pr. Hence the changes in this PR reference only a syntax update for the piece of code under review.
=> chore: update syntax to more modern usage
