rsksmart/rns-manager-react

README.md
Hi @ilanolkies ! :wave: 
Please review it when you've a while.
Kiss!
=> Fix typos - Readme

src/app/auth/components/AuthModalComponent.js, src/app/auth/components/StartButtonComponent.js, src/app/components/FieldComponent.js, src/app/components/GetDomainStateComponent.js, src/app/components/metamask/MetamaskButtonComponent.js, src/app/components/metamask/MetamaskFormComponent.js, src/app/containers/metamask/MetamaskButtonContainer.js, src/app/containers/metamask/MetamaskFormContainer.js, src/app/index.js, src/app/notifications/components/TxNotificationComponent.js, src/app/tabs/admin/components/AdminTabComponent.js, src/app/tabs/bid/components/BidComponent.js, src/app/tabs/finalize/containers/FinalizeContainer.js, src/app/tabs/multiChainResolver/components/MultiChainAddrFieldComponent.js, src/app/tabs/resolve/components/ResolutionComponent.js, src/app/tabs/resolve/components/ResolveAddrComponent.js, src/app/tabs/resolve/components/ResolveChainAddrComponent.js, src/app/tabs/resolve/components/ResolveComponent.js, src/app/tabs/search/components/DomainStateComponent.js, src/app/tabs/unseal/containers/UnsealContainer.js
=> Fix prop type validations

src/config/contracts.json
=> Fix reveal period length

src/app/components/GetDomainStateComponent.js, src/app/tabs/home/components/ResolveAddressComponent.js, src/app/tabs/resolve/components/ResolveComponent.js, src/app/tabs/search/components/DomainStateComponent.js, src/app/validations.js
=> Change name validation

src/app/routes.js
=> Can search and resolve with no metamask

package.json, yarn.lock
=> Fix eslint-utils version

src/app/tabs/resolve/components/ResolveQRComponent.js, src/app/tabs/resolve/containers/ResolveAddrContainer.js, src/app/tabs/resolve/containers/ResolveNameContainer.js
=> Renamed getAddr to getResolution so it can be used by both containers

src/config/contracts.json, src/config/contracts.prod.json
=> Added prod contracts addresses (#54)

src/app/components/GetDomainStateComponent.js, src/app/containers/GetDomainStateContainer.js
=> Disable search button when committing or committed to registrar

src/app/tabs/registrar/components/RegistrarComponent.js, src/app/tabs/registrar/containers/RegistrarContainer.js
=> Validate even when the user mounts

src/app/tabs/registrar/components/RegistrarComponent.js, src/app/tabs/registrar/components/RevealComponent.js
=> Do not allow empty or invalid names to be registered

src/app/tabs/registrar/components/RegistrarComponent.js, src/app/tabs/registrar/components/RevealComponent.js, src/languages/en.json
=> Added button to register a new name when finish a registration

src/app/auth/operations.js, src/app/components/FooterComponent.js, src/app/tabs/search/components/DomainStateComponent.js, src/app/tabs/search/containers/DomainStateContainer.js, src/assets/css/OverwriteBootstrap.css, src/assets/css/theming.css
This pull request addresses a few quality and consistency issues as well as redirecting to the admin page when logged in. 
- Redirect to admin page on successful login
- Fixes button classes to make disabled look disabled, and removes blue text on a blue button
- Fixes issue where <div.spinner> was nested inside of <p>. Removed the code since it was redundant. 
- Passes a react variable that was propTypes.required
=> Redirect on login

src/app/tabs/registrar/components/RentalPeriodComponent.js
=> Open link to buy RIF in new window

src/app/auth/components/AuthModalComponent.js, src/app/components/IndicatorLight.js, src/app/tabs/search/operations.js
The user might have no `window.web3` and should be able to search with no errors.
=> Fix cost calculation

src/app/components/ChecksumErrorComponent.js, src/app/components/FieldComponent.js, src/app/components/index.js, src/app/containers/ChecksumErrorContainer.js, src/app/containers/index.js, src/app/tabs/admin/components/SubdomainComponent.js, src/app/tabs/admin/components/TransferDomainComponent.js, src/assets/css/sass/_errorMessages.scss, src/assets/css/sass/_index.scss, src/languages/en.json
- Adds checksum checking and ability to convert to lowercase automatically.
- Converts address to lowercase before sending them to the contract
- Admin > set subdomain address (adds validation)
- Admin > Advanced > Set Owner
- Admin > Danger Zone > Transfer Domain 
- Resolver Change
- Public Resolver
Clicking 'convert' will automatically convert the <input /> box to lowercase and initiate the form submit button. The user's wallet will launch.
=> Fix checksum issues and validate address inputs

src/app/auth/operations.js, src/app/auth/reducer.js, src/app/components/HeaderComponent.js, src/app/containers/HeaderContainer.js, src/app/routes.js, src/app/tabs/error/index.js, src/app/tabs/user/containers/UserTabContainer.js, src/assets/css/sass/_header.scss
If the user has not logged out of the manager and navigates to a different page, reloads the page or browser, the manager will attempt to log in to the address saved in localStorage.
A few other things that had to be done for this to work smoothly:
- LogoutManager function created to reset the reducer to initial state, run the start method, then redirect to the homepage
- A link to logout was added to the header navigation
- Moved the location of localStorage.setItem() to after login is successful. This does not remove the input from the popup window in case the user types in their address wrong.
=> Auto login

src/app/tabs/registrar/components/RentalPeriodComponent.js
=> Change link to exchanges

src/app/tabs/SetUpTab.js, src/assets/css/sass/_index.scss, src/assets/css/sass/setupTab/_setup.scss
Changes the values on the setup page to be dynamic and inherit from the environment. 
Closes #134
=> Setup page network

src/app/tabs/registrar/containers/CommitContainer.js, src/app/tabs/registrar/containers/RevealContainer.js, src/app/tabs/registrar/operations.js
Allow duration and rifCost to persist via localStorage if the browser is closed or refreshed.
Closes #175
=> Duration and RifCost persist

src/app/tabs/search/abis.json, src/app/tabs/search/operations.js
When searching for domains, if it is available, see if it is registered in the auction first. If so, get the deedAddress, and then call the owner to get the owner. If not, carry on and get the owner from the rskOwner contract.
Closes #142
=> When domain is available, check if registered in the auction first

src/app/tabs/registrar/components/RegistrarComponent.js, src/app/tabs/registrar/containers/RegistrarContainer.js, src/app/tabs/registrar/operations.js
Allows the user to close or refresh the browser after they have paid their RIF but before the transaction is confirmed. 
Closes #132
=> Persist registration

src/app/auth/operations.js
Closes #194
It was not working with any browser with no wallet installed.
=> Fix auto login error

src/app/tabs/error/index.js
Use proper syntax. Found while working in the admin.
=> Fix propTypes error with strings.

package.json, src/app/tabs/admin/components/AdminTabComponent.js, yarn.lock
=> Fix ghpages

package.json, src/app/tabs/admin/components/AdminTabComponent.js, yarn.lock
=> Fix ghpages dev

src/app/components/FooterComponent.js
The placement is temporary until the new layout is complete. 
Closes #215
=> Add version to the footer

src/app/routes.js, src/app/tabs/faq/index.js, src/app/tabs/index.js, src/languages/en.json
- content to be added later once determined
- includes one language that needs translation
Part of #140
=> Create blank FAQ page and route

src/app/tabs/newAdmin/subdomains/operations.js
Do not return a value from function called with useEffect
- useEffect should not return a value which was causing the black screen issue
Closes #236
=> Fix blank screen when navigating away from Subdomain view

src/app/tabs/home/components/SearchBoxComponent.js, src/app/tabs/home/components/__snapshots__/SearchBoxComponent.test.js.snap
- Change Row to Form and add onSubmit handler.
- Update snapshot
Closes #245
=> Allow pressing 'enter' in search to search

src/app/tabs/newAdmin/resolver/operations.js
Value is sometimes passed with checksum caps so here it needs to be lowercase.
=> Convert value to lowercase before switch.

package.json, src/app/tabs/admin/components/AdminTabComponent.js, yarn.lock
This reverts commit a06a1b2a002235d1dc7961208338777e0973a3c7.
=> Revert "Add gh pages environment (#213)"

src/languages/en.json
This is an update to an existing text string. When we get translations back, I'll correct the other language files appropriately. 
Closes #257
=> Fix renew explanation text

src/app/components/AddressInputComponent.js, src/app/components/AddressInputComponent.test.js, src/app/tabs/newAdmin/addresses/components/AddNewAddressComponent.js, src/app/tabs/newAdmin/addresses/components/YourAddressesComponent.js, src/app/tabs/newAdmin/addresses/containers/AddNewAddressContainer.js, src/app/tabs/newAdmin/addresses/containers/YourAddressesContainer.js, src/app/tabs/newAdmin/helpers.js, src/app/tabs/newAdmin/helpers.test.js, src/app/tabs/newAdmin/resolver/components/NewRecordComponent.test.js, src/app/tabs/newAdmin/resolver/components/ResolverComponent.js, src/app/tabs/newAdmin/resolver/components/__snapshots__/NewRecordComponent.test.js.snap, src/app/tabs/newAdmin/resolver/containers/SetResolverContainer.js, src/app/tabs/newAdmin/reverse/components/ReverseComponent.js, src/app/tabs/newAdmin/reverse/containers/ReverseContainer.js, src/app/tabs/newAdmin/subdomains/components/NewSubdomainComponent.js, src/app/tabs/newAdmin/subdomains/components/SubdomainListComponent.js, src/app/tabs/newAdmin/subdomains/containers/NewSubdomainContainer.js, src/app/tabs/newAdmin/subdomains/containers/SubdomainListContainer.js, src/assets/css/sass/admin/_address.scss, src/assets/css/sass/admin/_index.scss, src/assets/css/sass/admin/_subdomains.scss, src/assets/css/sass/components/_addressInputComponent.scss, src/assets/css/sass/components/_index.scss, src/assets/css/sass/components/_suggestionsList.scss, src/languages/en.json
Adds suggestions to various prompts in the manager.
- Your Addresses: "RSK address"
- Subdomains: creating, and editing when the value is not the owners
- Resolver: (existing) when not set to the multichain resolver
- Reverse
It also adds CSS updates, placeholder, and prefix text strings.
Closes #268
=> Suggestions

src/app/tabs/newAdmin/containers/AdminTabContainer.js
Adding missing ...dispatchProps so the toggleSwitch method is accessible.
=> Fix toggle button

.github/workflows/deploy.yml
Hi.
Remember, this will only deploy if you config the corresponding secrets in your repo.
:D
=> CD added for MainNet

src/app/tabs/newAdmin/containers/AdminTabContainer.js, src/app/tabs/newAdmin/domainInfo/components/RenewButtonComponent.js, src/app/tabs/newAdmin/domainInfo/reducer.js
- Prevents the flash of "Expired Domain" when logging in.
- Fixes issue #336.
=> Set expires initial value to null rather than 0

package.json, src/app/auth/operations.js, src/languages/es_uy.json, yarn.lock
Reverts rnsdomains/rns-manager-react#376
=> Revert "v2.0.8"

package.json, src/app/rLogin/rLogin.js, yarn.lock
For testing, all the functions worked except setting a subdomain with a different owner. See below for full test results.
This is in Draft until the rLogin PR is merged & deployed: https://github.com/rsksmart/rLogin/pull/89 . It was tested locally with `yarn link`
=> Add Portis

yarn.lock
Reverts rnsdomains/rns-manager-react#414
=> Revert "Bump dns-packet from 1.3.1 to 1.3.4"

package.json, src/assets/css/sass/home/_index.scss
Uses the same strategy as the footer gray arch.
=> Fix curve home image

.gitignore, package.json, yarn.lock
This updates the rLogin package to the latest version.
=> feat: upgrade rlogin

src/app/auth/operations.js, src/app/rns-sdk.js
This PR allows the manager to use the RNS SDK for logging into the admin interface.
=> Use the RNS SDK for login

package.json, src/config/contracts.local.json, yarn.lock
This PR updates the rlogin dependency.
=> chore: update rlogin

src/languages/en.json, src/languages/pt_br.json
This PR addresses this [issue](https://rsklabs.atlassian.net/browse/RNS-458)
=> chore: use correct text on admin page for mulitichain resolver instead of mulitcoin

src/app/helpers/contentHash.js, src/app/tabs/newAdmin/resolver/operations.js
This PR addresses this [issue](https://rsklabs.atlassian.net/browse/RNS-457)
=> Fix decentralised url

src/app/components/FooterComponent.js
This PR updates the links on the dApp's footer and removes dud ones too.
=> chore: update footer links

src/app/tabs/newAdmin/subdomains/components/NewSubdomainComponent.js
This PR addresses a bug where owner input is still editable when the use different owner switch is not enabled
=> fix: ux improvement in new subdomain flow

src/app/tabs/home/components/SearchResultsComponent.js, src/app/tabs/home/components/SearchResultsComponent.test.js, src/app/tabs/home/components/__snapshots__/SearchResultsComponent.test.js.snap, src/assets/css/main.css, src/assets/css/sass/home/_searchResults.scss
=> fix: cosmetic issue with register button in Spanish

src/app/tabs/home/components/SearchResultsComponent.js, src/app/tabs/home/components/SearchResultsComponent.test.js, src/app/tabs/home/components/__snapshots__/SearchResultsComponent.test.js.snap, src/assets/css/sass/home/_searchResults.scss
This PR applies the changes mentioned in [this Jira tk](https://rsklabs.atlassian.net/jira/software/projects/REM/boards/265?selectedIssue=REM-34), initialy applied in [this PR](https://github.com/rsksmart/rns-manager-react/pull/546).
=> fix: cosmetic issue related to register button

src/app/components/FooterComponent.js
This PR updates the footer links of the manager specifically for this branch
=> fix: update footer links

src/app/auth/components/AuthModalComponent.js, src/app/auth/components/LoginFormComponent.js, src/app/tabs/newAdmin/domainInfo/containers/SetControllerContainer.js, src/app/tabs/newAdmin/domainInfo/containers/TransferAddressContainer.js, src/app/tabs/resolve/components/ResolveComponent.js, src/app/tabs/resolve/components/ResolveContentComponent.js, src/app/tabs/resolve/reducer.js
- Avoid having an empty page when visiting `/resolve`
- Fix some warnings/errors show in the browser logs
- [REM-45](https://rsklabs.atlassian.net/browse/REM-45)
=> REM-45: Fix error shown in console log

src/app/auth/components/LoginFormComponent.js, src/app/tabs/newAdmin/domainInfo/containers/SetControllerContainer.js, src/app/tabs/newAdmin/domainInfo/containers/TransferAddressContainer.js, src/app/tabs/resolve/components/ResolveComponent.js, src/app/tabs/resolve/components/ResolveContentComponent.js, src/app/tabs/resolve/reducer.js
- Avoid having an empty page when visiting `/resolve`
- Fix some warnings/errors show in the browser logs
- [REM-45](https://rsklabs.atlassian.net/browse/REM-45)
=> fix console errors

src/app/tabs/resolve/components/ResolveComponent.js, src/languages/es_uy.json
[REM-43](https://rsklabs.atlassian.net/browse/REM-43)
=> fix: removing multicoin view since the only network enabled is rsk REM-43

src/app/components/FooterComponent.js
This PR addresses this cosmetic update: [REM-46](https://rsklabs.atlassian.net/browse/REM-46)
=> chore: update company footer name brand
